version: '2'
services:
    php:
        links:
            - mysql
    data:
        image: tianon/true
        volumes:
            - ./tmp/mysql-data:/var/lib/mysql
        container_name: codesui-data
    mysql:
        image: mysql:latest
        volumes:
            - ./db:/docker-entrypoint-initdb.d
        volumes_from:
            - data
        environment:
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_DATABASE: "db"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
        ports:
            - 3333:3306
        command: mysqld --sql_mode=""
        container_name: codesui-mysql
        networks:
            - codesui-network
    nginx:
        build: ./dockers/nginx/
        ports:
            - 8888:8888
        expose:
            - 8888
        links:
            - php
        volumes_from:
            - app
        container_name: codesui-nginx
        networks:
            - codesui-network
    php:
        build: ./dockers/php/
        expose:
            - 8888
        volumes_from:
            - app
        container_name: codesui-php
        networks:
            - codesui-network
    app:
        image: tianon/true
        volumes:
            - ./src:/var/www/html
            - ./tmp/logs:/var/log/nginx
            - ./config/conf.d.2:/config
        container_name: codesui-app
        networks:
            - codesui-network
networks:
    codesui-network:
        driver: bridge
